ALGG-98 IDE 불러오기 버튼
cau-overchaos/frontend pull request #25
Opened 2023-11-15 15:53 UTC by LiteHell

코드랑 제목을 불러와줌.

2023-11-15 16:01 UTC, boulce requested changes
<img width="1101" alt="스크린샷 2023-11-16 오전 1 01 00" src="https://github.com/cau-overchaos/frontend/assets/83588265/fb7aef85-647c-4fd4-9f81-5bdc2079da34">

너비 넓게 고정시키면 좋을듯

2023-11-15 16:15 UTC, LiteHell commented
> <img alt="스크린샷 2023-11-16 오전 1 01 00" width="1101" src="https://user-images.githubusercontent.com/83588265/283174706-fb7aef85-647c-4fd4-9f81-5bdc2079da34.png">
> 
> 너비 넓게 고정시키면 좋을듯

300px 정도로 고정함

2023-11-16 01:26 UTC, boulce commented
<img width="551" alt="스크린샷 2023-11-16 오전 10 25 59" src="https://github.com/cau-overchaos/frontend/assets/83588265/a8b524a6-6872-4459-9910-41020e1dcec0">
<img width="389" alt="스크린샷 2023-11-16 오전 10 26 12" src="https://github.com/cau-overchaos/frontend/assets/83588265/ffcd6d4e-6218-46ff-b6d3-e22afda3ea1f">

프로그래밍 언어 목록 조회한게 제대로 안뜨는것 같은데?

2023-11-16 01:28 UTC, boulce commented
> <img alt="스크린샷 2023-11-16 오전 10 25 52" width="545" src="https://user-images.githubusercontent.com/83588265/283293160-e6d83022-e0a5-4912-9244-d4d84858d615.png"> <img alt="스크린샷 2023-11-16 오전 10 25 59" width="551" src="https://user-images.githubusercontent.com/83588265/283293099-a8b524a6-6872-4459-9910-41020e1dcec0.png"> <img alt="스크린샷 2023-11-16 오전 10 26 12" width="389" src="https://user-images.githubusercontent.com/83588265/283293103-ffcd6d4e-6218-46ff-b6d3-e22afda3ea1f.png">
> 프로그래밍 언어 목록 조회한게 제대로 안뜨는것 같은데?

아 정확히 말해서는 드롭다운 했을때 잘리는듯

2023-11-16 01:57 UTC, LiteHell commented
> > <img alt="스크린샷 2023-11-16 오전 10 25 52" width="545" src="https://user-images.githubusercontent.com/83588265/283293160-e6d83022-e0a5-4912-9244-d4d84858d615.png"> <img alt="스크린샷 2023-11-16 오전 10 25 59" width="551" src="https://user-images.githubusercontent.com/83588265/283293099-a8b524a6-6872-4459-9910-41020e1dcec0.png"> <img alt="스크린샷 2023-11-16 오전 10 26 12" width="389" src="https://user-images.githubusercontent.com/83588265/283293103-ffcd6d4e-6218-46ff-b6d3-e22afda3ea1f.png">
> > 프로그래밍 언어 목록 조회한게 제대로 안뜨는것 같은데?
> 
> 아 정확히 말해서는 드롭다운 했을때 잘리는듯

프로그래밍 언어도 표시하면 되는거지?

2023-11-16 02:00 UTC, boulce commented
> > > <img alt="스크린샷 2023-11-16 오전 10 25 52" width="545" src="https://user-images.githubusercontent.com/83588265/283293160-e6d83022-e0a5-4912-9244-d4d84858d615.png"> <img alt="스크린샷 2023-11-16 오전 10 25 59" width="551" src="https://user-images.githubusercontent.com/83588265/283293099-a8b524a6-6872-4459-9910-41020e1dcec0.png"> <img alt="스크린샷 2023-11-16 오전 10 26 12" width="389" src="https://user-images.githubusercontent.com/83588265/283293103-ffcd6d4e-6218-46ff-b6d3-e22afda3ea1f.png">
> > > 프로그래밍 언어 목록 조회한게 제대로 안뜨는것 같은데?
> > 
> > 
> > 아 정확히 말해서는 드롭다운 했을때 잘리는듯
> 
> 프로그래밍 언어도 표시하면 되는거지?

아 잘못 말했는데, 코드 목록 조회가 제대로 안된다고 하는 거였슴

2023-11-16 03:21 UTC, boulce approved these changes
LGTM

2023-11-16 03:31 UTC, merged